apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: taskmanager
data:
  APP_NAME: TaskManager
  APP_ENV: production
  APP_DEBUG: "false"
  APP_URL: http://backend:8000
  LOG_CHANNEL: stack
  LOG_LEVEL: info
  DB_CONNECTION: pgsql
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_DATABASE: taskmanager
  SANCTUM_STATEFUL_DOMAINS: frontend:3000
  SESSION_DOMAIN: backend 